### ISSUE TITLE
Plugin does not work in XL Release 5

### ISSUE THREAD

**Issue by gjvanhalem** [xebialabs-community/xlr-tfs-plugin#2]
In XL Release 5 the cifsPort field is used by the Windows Remote Script task. Therefor the server does not start when the TFS plugin is loaded. I fixed it locally by renaming the cifsPort field to cifsPortTfs. Changes need to be made in the synthetic.xml and the python scripts voor tfpt.
I was unable to create a pull request with my changes :-(

**Comment by jdewinne** [comment]
Hi,

What did go wrong when trying to create the pull request?

Regards,
Joris

**Comment by gjvanhalem** [comment]
9:03:29 Can't Create Pull Request
        Push failed:
        ERROR: Permission to xebialabs-community/xlr-tfs-plugin.git denied to deploy key
        Could not read from remote repository.

**Comment by istairbn** [comment]
Any update on a release with version 5 compatibility?

**Comment by jdewinne** [comment]
I've just tried using the plugin with XLR 5.0.1. It starts without any error, and I'm also able to add a tfpt task into a template. What is missing regarding version 5 compatibility?
