### ISSUE TITLE
Test Connection throws an ImportError

### ISSUE THREAD

**Issue by istairbn** [xebialabs-community/xlr-tfs-plugin#4]
Downloaded the latest release and installed, received the following error when trying test connection over Rest API:

Can't connect to Tfs: Server.
ImportError: No module named microsoft

Looks like it's relying on the TFS core modules for the NTLM

**Comment by jdewinne** [comment]
Did you install the sdk as described in the [readme](https://github.com/xebialabs-community/xlr-tfs-plugin#tfs-sdk)

**Comment by istairbn** [comment]
Aha! No, we're using 2015 so I've removed access to all but the REST API. 
I didn't realise that the SDK section would still be a requirement as it appears deprecated for older versions.
